name: Actualizar productos

on:
  repository_dispatch:
    types: [update_productos]

jobs:
  update-productos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Modificar productos.json
        run: |
          echo "${{ github.event.client_payload.content }}" | base64 --decode > productos.json

      - name: Commit & Push
        run: |
          git config user.name "Admin Web"
          git config user.email "admin@github"
          git add productos.json
          git commit -m "Actualizaci√≥n desde panel admin"
          git push

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
